### ISSUE TITLE
Create Wireframes

### ISSUE THREAD

**Issue by nswalters** [nss-evening-cohort-12/rare-publishing-sequoia#51]
WIREFRAMES FOR DAYS!!!!

**Comment by olamide87** [comment]
<img width="520" alt="Screen Shot 2020-10-31 at 2 45 24 PM" src="https://user-images.githubusercontent.com/59629698/97788587-1ebae880-1b88-11eb-858f-976fae8ca361.png">

**Comment by olamide87** [comment]
<img width="528" alt="Screen Shot 2020-10-31 at 2 38 02 PM" src="https://user-images.githubusercontent.com/59629698/97788590-25496000-1b88-11eb-8bef-0e6b1eca19e6.png">
